main/urls.py
from django.urls import path
from django.urls.conf import include
from main.views import *

app_name="main"
urlpatterns=[
    path('',showmain, name="showmain"),
    path('first/',first, name="first"),
    path('second/',second, name="second"),
    path('<str:id>',detail, name="detail"),
    path('new/',new,name="new"),
    path('create/',create, name="create"),
    path('edit/<str:id>',edit,name="edit"),
    path('update/<str:id>',update,name="update"),
    path('delete/<int:id>',delete,name="delete"),
    path('<str:blog_id>/create_comment', create_comment, name="create_comment"),
    path('cdelete/<str:id>',cdelete,name="cdelete"),
    path('cedit/<str:id>',cedit,name="cedit"),
    path('cupdate/<str:id>',cupdate,name="cupdate"),
    
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
  

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage', views.mypage, name="mypage"),
    path('<int:id>/follow',views.follow,name="follow"),
    
]

basic/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    id= models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User,on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image=models.ImageField(upload_to="blog/",blank=True, null=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]

class Comment(models.Model):
    id= models.AutoField(primary_key=True)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    

    def summary(self):
        return self.content

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    followings=models.ManyToManyField("self", related_name="followers", symmetrical=False)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

basic/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Blog, Comment
from django.utils import timezone

# Create your views here.


from django.contrib import admin
from django.urls import path
from main import views


def showmain(request):
    blogs=Blog.objects.all()
    return render(request, 'main/mainpage.html',{'blogs':blogs})

def first(request):
    return render(request, 'main/first.html')

def second(request):
    return render(request, 'main/second.html')

def detail(request,id):
    blog=get_object_or_404(Blog, pk=id)
    all_comments=blog.comments.all().order_by('-created_at')
    return render(request,'main/detail.html',{'blog':blog,'comments':all_comments})

def new(request):
    return render(request, 'main/new.html')

def create(request):
    new_blog = Blog()
    new_blog.title = request.POST['title']
    new_blog.writer = request.user
    new_blog.pub_date = timezone.now()
    new_blog.body = request.POST['body']
    new_blog.image=request.FILES.get('image')
    new_blog.save()
    return redirect('main:detail',new_blog.id)

def edit(request,id):
    edit_blog=Blog.objects.get(id=id)
    return render(request, 'main/edit.html',{'blog':edit_blog})

def update(request,id):
    update_blog = Blog.objects.get(id=id)
    update_blog.title = request.POST['title']
    update_blog.writer = request.user
    update_blog.pub_date = timezone.now()
    update_blog.image=request.FILES.get('image')
    update_blog.body = request.POST['body']
    update_blog.save()
    return redirect('main:detail',update_blog.id)

def delete(request,id):
    delete_blog=Blog.objects.get(id=id)
    delete_blog.delete()
    return redirect('main:showmain')
    
def create_comment(request, blog_id):
	if request.method == "POST":
		blog = get_object_or_404(Blog, pk=blog_id)
		current_user = request.user
		comment_content = request.POST.get('content')
		Comment.objects.create(content=comment_content, writer=current_user, blog=blog)
	return redirect('main:detail', blog_id)

def cdelete(request,id):
    cdelete_comment=Comment.objects.get(id=id)
    cdelete_comment.delete()
    return redirect('main:showmain')

def cedit(request,id):
    edit_comment=Comment.objects.get(id=id)
    return render(request, 'main/cedit.html',{'comment':edit_comment})

def cupdate(request,id):
    update_comment = Comment.objects.get(id=id)
    update_comment.writer = request.user
    update_comment.pub_date = timezone.now()
    update_comment.content = request.POST.get('content')
    update_comment.save()
    return redirect('main:showmain')


    

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from main.models import Blog
from .models import User

# Create your views here.
def mypage(request, id):
    user=get_object_or_404(User,pk=id)
    context={
        'user':user,
        'blogs':Blog.objects.filter(writer=user),
        'followings':user.profile.followings.all(),
        'followers':user.profile.followers.all(),
    }
    return render(request,'users/mypage.html', context)


def follow(request,id):
    user=request.user
    followed_user=get_object_or_404(User,pk=id)
    is_follower=user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

basic/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>mandu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    
    <style>
    *{font-family: 'Jua', sans-serif;}
    h1{
         color:dimgray;
         font-weight: bolder;
         font-size: 70px;
     } 
     div{
         font-size: 20px;
         margin-bottom: 10px;
     }  
     table{
         font-size: 18px;
     }
     nav{
            height: 30px;
        }
       
     </style>
</head>



<body>
    {% include 'shared/_navbar.html' %}  

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    </body>
    </html>

basic/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">JAE-GYEONG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authengicated %}
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
            <li><a class="dropdown-item" href="{% url 'users:mypage' %}">Mypage</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'account_login' %}">Login</a></li>
            <li><a class="dropdown-item" href="{% url 'account_signup' %}">Signup</a></li>
            {% endif %}
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        </ul>
        <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
    </div>
</nav>              

main/templates/accont/login.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account socialaccount %}
{% providers_media_js %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

<h1>{% trans "Sign In" %}</h1>

{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<p>{% blocktrans with site.name as site_name %}Please sign in with one
of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

<div class="socialaccount_ballot">

  <ul class="socialaccount_providers">
    {% include "socialaccount/snippets/provider_list.html" with process="login" %}
  </ul>

  <div class="login-or">{% trans 'or' %}</div>

</div>

{% include "socialaccount/snippets/login_extra.html" %}

{% else %}
<p>{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endif %}

<form class="login" method="POST" action="{% url 'account_login' %}">
  {% csrf_token %}
  {{ form.as_p }}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
  <button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
</form>

{% endblock %}

main/templates/main/cedit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div>
	<form action="{%url 'main:cupdate' comment.id%}" method="POST">
		{%csrf_token%}
		<p><textarea name="content" id="" placeholder="댓글내용입력">{{comment.content}}</textarea></p>
		<input type="submit" value="확인">
	</form>
</div>

{% endblock %}

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{blog.title}}</h1>
{% if blog.writer %}
{% if 'user' in blog.writer.username %}
<h3>작성자 :<a href="{% url 'users:mypage' blog.writer.id %}"> {{ blog.writer.last_name }} {{ blog.writer.first_name }}</a></h3>
{% else %}
<h3>작성자 :<a href="{% url 'users:mypage' blog.writer.id %}"> {{ blog.writer }}</a></h3>
{% endif %}
{% else %}
<h3>작성자 : 알 수 없음</h3>
{% endif %}<br>
날짜 : {{blog.pub_date}}
<hr>
{% if blog.image %}
    <p><img src="{{ blog.image.url }}"alt="사진"></p>
{% endif %}

<p>{{blog.body}}</p>
<a href="{% url 'main:edit' blog.id %}">수정하기</a>
<a href="{% url 'main:delete' blog.id %}">삭제하기</a>

<div>
	<form action="{%url 'main:create_comment' blog.id%}" method="POST">
		{%csrf_token%}
		<textarea name="content" placeholder="댓글내용입력"></textarea>
		<input type="submit" value="확인">
	</form>
</div>


<div>
    {% for comment in comments %}
    <div>
        작성자: {{comment.writer}}<br>
        내용: {{comment.content}}
    </div>
    <a href="{% url 'main:cedit' comment.id %}">수정하기</a>
    <a href="{% url 'main:cdelete' comment.id %}">삭제하기</a>
    {% endfor %}
</div>

{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>글 수정하기</h1>
    <form action="{% url 'main:update' blog.id %}" method="post" enctype="multipart/form-data" >
	    {%csrf_token%}
	    <p>제목 : <input type="text" name="title" value="{{blog.title}}"></p>
	    <p>작성자 : </p>
		<p>사진: <input type="file" name="image"></p>
	    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10">{{blog.body}}</textarea></p>
	    <button type="submit">제출</button>
    </form>
</div>

<div>

</div>
{% endblock %}

main/templates/main/first.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1 class="hi" style="text-align:center;">만두는 누구인가?</h1>
  <hr style="border-style: dotted; color: darkgrey;" >
  
  <div style="text-align:center;">
  
     <li>&#128054; 2018년 7월 2일생 </li> 
     <li>&#128054; 포메라니안</li>
     <li>&#128054; 왕자</li>
  
  </div>

  <table style="margin-left: auto; margin-right: auto;">
    <tr> <!--사진-->
        <td><img src="{% static 'images/식탐.jpg' %}" width=300 height=300></td>
        <td><img src="{% static 'images/통통.jpg' %}" width=300 height=300></td>
        <td><img src="{% static 'images/산책.jpg' %}" width=300 height=300></td>
    </tr>
    <tr style="text-align:center;"> <!--글-->
        <td>식탐이 많아요</td>
        <td>조금 통통해요</td>
        <td>산책을 좋아해요</td>
    </tr>
    <tr> <!--사진-->
        <td><img src="{% static 'images/고양이.jpg' %}" width=300 height=300></td>
        <td><img src="{% static 'images/다리.jpg' %}" width=300 height=300></td>
        <td><img src="{% static 'images/모자.jpg' %}" width=300 height=300></td>
    </tr>
    <tr style="text-align:center;"> <!--글-->
        <td>고양이를 좋아해요</td>
        <td>다리가 짧아요</td>
        <td>모자 쓰는 것을 싫어해요</td>
    </tr>
  </table>
  {% endblock %}

main/templates/main/mainpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JAE GYEONG</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Jua&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/JJG.css' %}">
    
    <style media="screen">
        div{width: 100vw; height:100vh;}
        *{font-family: 'Jua', sans-serif;}
        nav{
            height: 34px;
        }
       
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">JAE-GYEONG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout </a></li>
                <li><a class="dropdown-item" href="{% url 'users:mypage' request.user.id %}">Mypage</a></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'account_login' %}">Login</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'account_signup' %}">Signup</a></li>
                {% endif %}
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            </ul>
            <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        </div>
    </nav>
    <section>
        <div id="window1">
            <div id ="intro">
                <h1>WHO IS JAE-GYEONG?</h1>
                <h3>궁금하면 내려보세요!</h3>
            </div>
        </div>

        <div id="window2">
            <img src="{% static 'images/computer.png' %}">
            <div id="myself">
                <h1>개발자가 되고 싶어요!</h1>
                <h2>저는 원래 법조인을 꿈꿨지만 이제는 개발자라는 꿈을 꾸고 있습니다. </h2>
            </div>
        </div>

        <div id="window3">
            <h1>&#128584;MY KEYWORD &#128584; </h1>

            <div class="container">
                <div class="keyword">
                    <img class="keyword_img" src="{% static 'images/밀리의서재.png' %}" alt="밀리의 서재 사진">
                    <p class="keyword_text"><a href="{% url 'main:second' %}">책</a> 읽는 걸 좋아해요. 특히 밀리의 서재로! </p>
                </div>
                <div class="keyword">
                    <img class="keyword_img" src="{% static 'images/mandu.jpg.png' %}" alt="만두 사진">
                    <p class="keyword_text">3살 포메, <a href="{% url 'main:first' %}">만두</a>의 누나. 인스타 아이디도 mandu_sister ! </p>
                </div>
                <div class="keyword">
                    <img class="keyword_img" src="{% static 'images/서점.png' %}"alt="서점 사진">
                    <p class="keyword_text">서점 투어가 취미이자 나만의 힐링 방법</p>
                </div>
            </div>
        </div>

        <div id="window4">
            <h1>&#128218; 재경 사전 &#128218;</h1>
            <div class="tmicontainer">
                <div class="tmilist">
                    <p id="tmi1">생일은?</p>
                    <p id="tmi2">가족은?</p>
                    <p id="tmi3">고향은?</p>
                </div>
                <div class="tmilist">
                    <p id="tmi4">민초 좋아해?</p>
                    <p id="tmi5">좋아하는 색은?</p>
                    <p id="tmi6">무서워하는 것은?</p>
                </div>
                <div class="tmilist">
                    <p id="tmi7">좋아하는 햄버거는?</p>
                    <p id="tmi8">커피 마셔?</p>
                    <p id="tmi9">MBTI?</p>
                </div>
            </div>
        </div>

        <div id="window5">
            <h1>&#129392;나의 넷플릭스 취향이 궁금하다면?&#129392;</h1>
            <div class="imglist">
                <a href="https://www.youtube.com/watch?v=IWpBGln6bNk" style="height: 376px;">
                    <img src="{% static 'images/넷플.png' %}" alt="리틀포레스트 예고편">
                </a>
                <a href="https://www.youtube.com/watch?v=JVq7VpOh49I" style="height: 376px;">
                    <img src="{% static 'images/넷플.png' %}" alt="엘리트들 소개영상">
                </a>
                <a href="https://www.youtube.com/watch?v=krNbUA7
                YWhg&list=PLDs8E0XdJ8TcFFBhjgSB82sV_Nvge0U6x&index=2" style="height: 376px;">
                    <img src="{% static 'images/넷플.png' %}" alt="터널 정주행 영상">
                </a>
                <a href="https://www.youtube.com/watch?v=HhgcXuN0MlU" style="height: 376px;">
                    <img src="{% static 'images/넷플.png' %}" alt="스위트홈 소개 영상">
                </a>
            </div>

        </div>

        <div> 
            <h2 style="margin-top: 200px; text-align: center; font-size: 64px;"><a href="{% url 'main:new' %}">방명록 쓰기</a></h2>
            <h1 style="margin-top: 100px; text-align: center; font-size: 70px;">방명록</h1>
            {% if user.is_authenticated %}
            <div id="hello">
                {% for blog in blogs %}
	            <div style="height: fit-content; text-align: center;" >
		            <h3 style="font-size: 35px;">{{blog.title}}</h3>
                    {% if blog.writer %}
                    {% if 'user' in blog.writer.username %}
                    <h3>작성자 : <a href="{% url 'users:mypage' blog.writer.id %}">{{ blog.writer.last_name }} {{ blog.writer.first_name }}</a></h3>
                    {% else %}
                    <h3>작성자 :<a href="{% url 'users:mypage' blog.writer.id %}"> {{ blog.writer }}</a></h3>
                    {% endif %}
                    {% else %}
                    <h3>작성자 : 알 수 없음</h3>
                    {% endif %}<br>
		            {{blog.summary}}
                    <a href="{% url 'main:detail' blog.id %}">...자세히</a>
		            <br>
	            </div>
	            {%endfor%}
            </div>
            {% else %}
            <h3>로그인 후 이용 가능</h3>
            <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
            <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
            {% endif %}
        </div>
        
    </section>
 
</body>
</html>

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'main:create'%}" method="post" enctype="multipart/form-data">
	{%csrf_token%}
	<p>제목 : <input type="text" name="title"></p>
	<p>작성자 : </p>
	<p>사진: <input type="file" name="image"></p>
	<p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
	<button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/second.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1 class="hi" style="text-align:center;">독서 초보가 추천하는 책</h1>
  <hr style="border-style: dotted; color: darkgrey;" >
  
  <div style="text-align:center;">
  
     <li>&#128213; 방법: 밀리의 서재 </li> 
     <li>&#128215; 언제? 자기 전이나 이동 시간</li>
     <li>&#128216; 좋아하는 분야? 경영 경제&에세이</li>
  
  </div>

  <table style="margin-left: auto; margin-right: auto;">
    <tr id=up> <!--사진-->
        <td><img src="{% static 'images/바이러스.JPG' %}" width=300 height=400></td>
        <td><img src="{% static 'images/네이버.jpeg' %}" width=300 height=400></td>
    </tr>
    <tr style="text-align:center;"> <!--글-->
        <td>개인적으로 좋아하는 작가님</td>
        <td>핀테크에 대해 알 수 있는 책</td>
    </tr>
    <tr id=down> <!--사진-->
        <td><img src="{% static 'images/집 청소.png' %}" width=300 height=400></td>
        <td><img src="{% static 'images/배민다움.jpg' %}" width=300 height=400></td>
    </tr>
    <tr style="text-align:center;"> <!--글-->
        <td>죽음의 흔적에 대한 적나라한 묘사가 <br> 독자로 하여금 많은 생각을 하게 하는 책</td>
        <td>성공한 사람의 생각을 알 수 있는 책</td>
    </tr>
  </table>
  {% endblock %}

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>
    {% if 'user' in user.username and user.username != 'user' %}
        {{ user.last_name }} {{ user.first_name }}
    {% else %}
        {{ user.username }}
    {% endif %}
    </h1>

    {% if request.user != user %}<!--다른 사람의 프로필에 들어온 경우에만 팔로우/언팔로우 버튼이보임-->
        {% if request.user.profile in user.profile.followers.all %}
            <a href="{%url 'users:follow' user.id %}"><button type="button" class="btn btn-outline-info">언팔로우</button></a>
        {% else %}
        <a href="{%url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
        {% endif %}
    {% endif %}
    </h1>
    <div class="container">
        <h3>팔로워{{user.profile.followers.count}}명</h3>
        {%for follower in user.profile.followers.all %}
            <a href="{% url 'users:mypage' follower.user.id %}">{{follower.user.username}}</a>
        {% endfor %}
        <h3>팔로잉{{user.profile.followings.count}}명</h3>
        {% for following in user.profile.followings.all %}
            <a href="{%url 'users:mypage' following.user.id%}">{{following.user.username}}</a>
        {% endfor %}
        </div>
    <div>
        {% for blog in blogs %}
            <a href="{%url 'main:detail' blog.id%}">{{blog.title}}</a><hr>
        {%endfor%}
    </div>
</div>
{% endblock %}